-- PostgreSQL clean schema for new Pharus databases (no legacy UUID paths)
-- Usage:
--   psql -U postgres -d pharus -f sql/pharus_local.sql

CREATE TABLE IF NOT EXISTS permission_groups (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  description TEXT NULL,
  status TEXT NOT NULL DEFAULT 'active',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS app_users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  raw_user_meta_data JSONB NOT NULL DEFAULT '{}'::jsonb,
  role TEXT NOT NULL DEFAULT 'user',
  permission_group_id BIGINT NULL REFERENCES permission_groups(id) ON DELETE SET NULL,
  status TEXT NOT NULL DEFAULT 'active',
  last_sign_in_at TIMESTAMPTZ NULL,
  last_seen_at TIMESTAMPTZ NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS columns (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  type TEXT NOT NULL,
  position INTEGER NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS clients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  acronym TEXT NULL,
  contact_name TEXT NULL,
  email TEXT NULL,
  phone TEXT NULL,
  cnpj TEXT NULL,
  municipal_registration TEXT NULL,
  state_registration TEXT NULL,
  address_street TEXT NULL,
  address_number TEXT NULL,
  address_complement TEXT NULL,
  address_district TEXT NULL,
  address_city TEXT NULL,
  address_state TEXT NULL,
  address_zip_code TEXT NULL,
  remote_tool TEXT NULL,
  remote_access_id TEXT NULL,
  remote_password TEXT NULL,
  remote_notes TEXT NULL,
  remote_connections JSONB NULL,
  status TEXT NOT NULL DEFAULT 'active',
  notes TEXT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS atendimentos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT NULL,
  client_id BIGINT NULL REFERENCES clients(id) ON DELETE SET NULL,
  status TEXT NOT NULL DEFAULT 'open',
  priority TEXT NOT NULL DEFAULT 'medium',
  created_by BIGINT NULL REFERENCES app_users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS atendimento_responsibles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  atendimento_id BIGINT NOT NULL REFERENCES atendimentos(id) ON DELETE CASCADE,
  user_id BIGINT NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_atendimento_responsible UNIQUE (atendimento_id, user_id)
);

CREATE TABLE IF NOT EXISTS atendimento_task_links (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  atendimento_id BIGINT NOT NULL REFERENCES atendimentos(id) ON DELETE CASCADE,
  task_id BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_atendimento_task_link UNIQUE (atendimento_id, task_id)
);

CREATE TABLE IF NOT EXISTS atendimento_comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  atendimento_id BIGINT NOT NULL REFERENCES atendimentos(id) ON DELETE CASCADE,
  author_id BIGINT NULL REFERENCES app_users(id) ON DELETE SET NULL,
  comment_text TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS atendimento_attachments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  atendimento_id BIGINT NOT NULL REFERENCES atendimentos(id) ON DELETE CASCADE,
  file_name TEXT NOT NULL,
  file_type TEXT NULL,
  file_size BIGINT NULL,
  data_url TEXT NOT NULL,
  uploaded_by BIGINT NULL REFERENCES app_users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  priority TEXT NOT NULL DEFAULT 'medium',
  assignee BIGINT NULL REFERENCES app_users(id) ON DELETE SET NULL,
  request_date DATE NULL,
  due_date DATE NULL,
  observation TEXT NULL,
  jira TEXT NULL,
  client TEXT NULL,
  attachment_name TEXT NULL,
  attachment_path TEXT NULL,
  attachment_type TEXT NULL,
  attachment_size INTEGER NULL,
  attachment_data TEXT NULL,
  is_pinned BOOLEAN NOT NULL DEFAULT FALSE,
  focus_order INTEGER NULL,
  type TEXT NOT NULL DEFAULT 'task',
  board_column_id BIGINT NULL REFERENCES columns(id) ON DELETE SET NULL,
  completed BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS chat_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_id BIGINT NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
  receiver_id BIGINT NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
  message TEXT NOT NULL,
  attachment_name TEXT NULL,
  attachment_path TEXT NULL,
  attachment_type TEXT NULL,
  attachment_size BIGINT NULL,
  edited_at TIMESTAMPTZ NULL,
  is_read BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS permission_group_rules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id BIGINT NOT NULL REFERENCES permission_groups(id) ON DELETE CASCADE,
  screen_key TEXT NOT NULL,
  option_key TEXT NOT NULL,
  allowed BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_permission_group_rule UNIQUE (group_id, screen_key, option_key)
);

CREATE TABLE IF NOT EXISTS agenda_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT NULL,
  event_type TEXT NOT NULL DEFAULT 'event',
  status TEXT NOT NULL DEFAULT 'pending',
  start_at TIMESTAMPTZ NOT NULL,
  end_at TIMESTAMPTZ NULL,
  is_all_day BOOLEAN NOT NULL DEFAULT FALSE,
  event_color TEXT NULL,
  created_by BIGINT NULL REFERENCES app_users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS notice_board_posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  priority TEXT NOT NULL DEFAULT 'medium',
  status TEXT NOT NULL DEFAULT 'active',
  visible_until DATE NULL,
  permission_group_id BIGINT NULL REFERENCES permission_groups(id) ON DELETE SET NULL,
  created_by BIGINT NULL REFERENCES app_users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS task_report_definitions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT NULL,
  owner_user_id BIGINT NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
  visibility TEXT NOT NULL DEFAULT 'private',
  definition_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  status TEXT NOT NULL DEFAULT 'active',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS task_report_group_shares (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_id BIGINT NOT NULL REFERENCES task_report_definitions(id) ON DELETE CASCADE,
  group_id BIGINT NOT NULL REFERENCES permission_groups(id) ON DELETE CASCADE,
  created_by BIGINT NULL REFERENCES app_users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_task_report_group_share UNIQUE (report_id, group_id)
);

CREATE OR REPLACE VIEW user_profiles AS
SELECT
  u.id,
  u.email,
  COALESCE(u.raw_user_meta_data->>'full_name', split_part(u.email, '@', 1)) AS full_name,
  u.role,
  u.status,
  u.last_sign_in_at,
  u.last_seen_at,
  u.created_at,
  u.updated_at
FROM app_users u;

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_app_users_updated_at') THEN
    CREATE TRIGGER trg_app_users_updated_at
    BEFORE UPDATE ON app_users
    FOR EACH ROW
    EXECUTE PROCEDURE set_updated_at();
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_columns_updated_at') THEN
    CREATE TRIGGER trg_columns_updated_at
    BEFORE UPDATE ON columns
    FOR EACH ROW
    EXECUTE PROCEDURE set_updated_at();
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_tasks_updated_at') THEN
    CREATE TRIGGER trg_tasks_updated_at
    BEFORE UPDATE ON tasks
    FOR EACH ROW
    EXECUTE PROCEDURE set_updated_at();
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_clients_updated_at') THEN
    CREATE TRIGGER trg_clients_updated_at
    BEFORE UPDATE ON clients
    FOR EACH ROW
    EXECUTE PROCEDURE set_updated_at();
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_atendimentos_updated_at') THEN
    CREATE TRIGGER trg_atendimentos_updated_at
    BEFORE UPDATE ON atendimentos
    FOR EACH ROW
    EXECUTE PROCEDURE set_updated_at();
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_permission_groups_updated_at') THEN
    CREATE TRIGGER trg_permission_groups_updated_at
    BEFORE UPDATE ON permission_groups
    FOR EACH ROW
    EXECUTE PROCEDURE set_updated_at();
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_agenda_events_updated_at') THEN
    CREATE TRIGGER trg_agenda_events_updated_at
    BEFORE UPDATE ON agenda_events
    FOR EACH ROW
    EXECUTE PROCEDURE set_updated_at();
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_notice_board_posts_updated_at') THEN
    CREATE TRIGGER trg_notice_board_posts_updated_at
    BEFORE UPDATE ON notice_board_posts
    FOR EACH ROW
    EXECUTE PROCEDURE set_updated_at();
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_task_report_definitions_updated_at') THEN
    CREATE TRIGGER trg_task_report_definitions_updated_at
    BEFORE UPDATE ON task_report_definitions
    FOR EACH ROW
    EXECUTE PROCEDURE set_updated_at();
  END IF;
END;
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'fk_atendimento_task_links_task'
  ) THEN
    ALTER TABLE atendimento_task_links
      ADD CONSTRAINT fk_atendimento_task_links_task
      FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE;
  END IF;
END;
$$;

INSERT INTO columns (title, type, position)
SELECT 'Pendente', 'pending', 0
WHERE NOT EXISTS (SELECT 1 FROM columns WHERE type = 'pending');

INSERT INTO columns (title, type, position)
SELECT 'Em Andamento', 'in_progress', 1
WHERE NOT EXISTS (SELECT 1 FROM columns WHERE type = 'in_progress');

INSERT INTO columns (title, type, position)
SELECT 'Em Teste', 'review', 2
WHERE NOT EXISTS (SELECT 1 FROM columns WHERE type = 'review');

INSERT INTO columns (title, type, position)
SELECT 'Concluído', 'completed', 3
WHERE NOT EXISTS (SELECT 1 FROM columns WHERE type = 'completed');

INSERT INTO permission_groups (name, description, status)
SELECT 'Administradores', 'Acesso total ao sistema', 'active'
WHERE NOT EXISTS (
  SELECT 1 FROM permission_groups WHERE name = 'Administradores'
);

INSERT INTO permission_groups (name, description, status)
SELECT 'Operacao', 'Uso diario com manutencao de tarefas e clientes', 'active'
WHERE NOT EXISTS (
  SELECT 1 FROM permission_groups WHERE name = 'Operacao'
);

INSERT INTO permission_groups (name, description, status)
SELECT 'Leitura', 'Consulta sem alteracoes', 'active'
WHERE NOT EXISTS (
  SELECT 1 FROM permission_groups WHERE name = 'Leitura'
);

INSERT INTO permission_group_rules (group_id, screen_key, option_key, allowed)
SELECT
  pg.id,
  perms.screen_key,
  perms.option_key,
  TRUE
FROM permission_groups pg
CROSS JOIN (
  VALUES
    ('dashboard', 'view'),
    ('dashboard', 'widgets'),
    ('agenda', 'view'),
    ('agenda', 'create'),
    ('agenda', 'edit'),
    ('agenda', 'delete'),
    ('agenda', 'complete'),
    ('avisos', 'view'),
    ('avisos', 'create'),
    ('avisos', 'edit'),
    ('avisos', 'delete'),
    ('avisos', 'archive'),
    ('quadro_tarefas', 'view'),
    ('quadro_tarefas', 'create'),
    ('quadro_tarefas', 'edit'),
    ('quadro_tarefas', 'move'),
    ('quadro_tarefas', 'delete'),
    ('quadro_tarefas', 'pin'),
    ('quadro_tarefas', 'filter'),
    ('quadro_tarefas', 'sort'),
    ('quadro_tarefas', 'import'),
    ('quadro_tarefas', 'attachment'),
    ('clientes', 'view'),
    ('clientes', 'create'),
    ('clientes', 'edit'),
    ('clientes', 'delete'),
    ('atendimento', 'view'),
    ('atendimento', 'create'),
    ('atendimento', 'edit'),
    ('atendimento', 'delete'),
    ('atendimento', 'assign'),
    ('atendimento', 'comment'),
    ('atendimento', 'attachment'),
    ('atendimento', 'link_task'),
    ('usuarios', 'view'),
    ('usuarios', 'create'),
    ('usuarios', 'edit'),
    ('usuarios', 'delete'),
    ('usuarios', 'chat'),
    ('chat', 'view'),
    ('chat', 'send'),
    ('chat', 'attachment'),
    ('relatorios', 'view'),
    ('relatorios', 'create'),
    ('relatorios', 'edit'),
    ('relatorios', 'share'),
    ('relatorios', 'export'),
    ('configuracoes', 'view'),
    ('configuracoes', 'project'),
    ('configuracoes', 'permissions'),
    ('configuracoes', 'users'),
    ('configuracoes', 'table'),
    ('configuracoes', 'extension'),
    ('configuracoes', 'maintenance')
) AS perms(screen_key, option_key)
WHERE pg.name = 'Administradores'
ON CONFLICT (group_id, screen_key, option_key)
DO UPDATE SET allowed = EXCLUDED.allowed;

INSERT INTO app_users (email, password, raw_user_meta_data, role, permission_group_id, status, last_sign_in_at)
SELECT
  'admin@pharus.local',
  'admin123',
  '{"full_name":"Administrador Local"}'::jsonb,
  'admin',
  (SELECT id FROM permission_groups WHERE name = 'Administradores' LIMIT 1),
  'active',
  NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM app_users WHERE email = 'admin@pharus.local'
);

UPDATE app_users
SET permission_group_id = (
  SELECT id FROM permission_groups WHERE name = 'Administradores' LIMIT 1
)
WHERE role = 'admin'
   OR LOWER(email) = 'admin@pharus.local';

DO $$
DECLARE
  agenda_max_id BIGINT;
BEGIN
  SELECT COALESCE(MAX(id), 0) INTO agenda_max_id FROM agenda_events;

  IF agenda_max_id > 0 THEN
    PERFORM setval('agenda_events_id_seq', agenda_max_id, true);
  ELSE
    PERFORM setval('agenda_events_id_seq', 1, false);
  END IF;
END;
$$;

